### ISSUE TITLE
requirements.txt

### ISSUE THREAD

**Issue by psifertex** [pbiernat/ripr#23]
The BN plugin manager will now automatically install dependencies specified in a [requirements.txt](https://pip.pypa.io/en/stable/reference/requirements-file-format/). 

It _looks_ like the only dependency needed there is unicorn maybe with a pinned version if one has been better tested?

**Comment by pbiernat** [comment]
Although the output of ripr is a script that uses unicorn for emulation, ripr itself does not require it to function. Because of this, I think it is unnecessary to force users to install unicorn on the same system they are running Binary Ninja. 

For example, you may want to generate a ripr-script on your Windows "Analysis" box, then upload that script to a server or transfer it to a local VM to actually run it/integrate it into whatever you're working on.
